// AUTO-GENERATED by tools/split-data.js — slim metadata only.
// Full lesson content lives in /web/data/<id>.json and is fetched on demand.
const DAYS = [
  {
    "id": "day-1",
    "code": "J1",
    "title": {
      "fr": "Jour 1 - chap1 PHP Basics",
      "en": "Day 1 - chap1 PHP Basics"
    },
    "sub": {
      "fr": "Syntaxe, types, operateurs, control flow, includes, printf",
      "en": "Syntax, types, operators, control flow, includes, printf"
    },
    "tags": [
      "chap1",
      "syntax",
      "types",
      "loops",
      "include",
      "printf"
    ],
    "why": {
      "fr": "Fondations CNAM NFA042 chap1. La quasi-totalite des QCM (10 points sur 20) viennent d'ici. A maitriser avant de toucher SQL/PDO.",
      "en": "CNAM NFA042 chap1 foundations. Nearly all MCQ marks (10/20) come from here. Master before touching SQL/PDO."
    },
    "exercises": [
      {
        "num": 1,
        "title": "Hello NFA042",
        "diff": "easy"
      },
      {
        "num": 2,
        "title": "Variables",
        "diff": "easy"
      },
      {
        "num": 3,
        "title": "Pair / Impair",
        "diff": "easy"
      },
      {
        "num": 4,
        "title": "Boucle 1-10",
        "diff": "easy"
      },
      {
        "num": 5,
        "title": "Somme 1-100",
        "diff": "easy"
      },
      {
        "num": 6,
        "title": "Categorie age",
        "diff": "medium"
      },
      {
        "num": 7,
        "title": "Table de 7",
        "diff": "medium"
      },
      {
        "num": 8,
        "title": "FizzBuzz",
        "diff": "medium"
      },
      {
        "num": 9,
        "title": "Switch role universite",
        "diff": "medium"
      },
      {
        "num": 10,
        "title": "Compte a rebours",
        "diff": "medium"
      },
      {
        "num": 11,
        "title": "Filtrer etudiants admis",
        "diff": "hard"
      },
      {
        "num": 12,
        "title": "Triangle d'etoiles",
        "diff": "hard"
      },
      {
        "num": 13,
        "title": "Min / Max",
        "diff": "hard"
      },
      {
        "num": 14,
        "title": "Premier impair",
        "diff": "hard"
      },
      {
        "num": 15,
        "title": "Inverser chaine",
        "diff": "hard"
      },
      {
        "num": 16,
        "title": "Multiples de 3",
        "diff": "extreme"
      },
      {
        "num": 17,
        "title": "in_array",
        "diff": "extreme"
      },
      {
        "num": 18,
        "title": "Tri etudiants admis par note",
        "diff": "extreme"
      },
      {
        "num": 19,
        "title": "Pyramide centree",
        "diff": "extreme"
      },
      {
        "num": 20,
        "title": "Mini calculatrice",
        "diff": "extreme"
      }
    ],
    "problemes": [
      {
        "num": 101,
        "title": "Problème 01",
        "diff": "extreme"
      },
      {
        "num": 102,
        "title": "Problème 02",
        "diff": "extreme"
      },
      {
        "num": 103,
        "title": "Problème 03",
        "diff": "extreme"
      },
      {
        "num": 104,
        "title": "Problème 04",
        "diff": "extreme"
      },
      {
        "num": 105,
        "title": "EXAM 2023-2024 Session 2 — Ex.1 Compléter le code (2 pts)",
        "diff": "extreme"
      }
    ]
  },
  {
    "id": "day-2",
    "code": "J2",
    "title": {
      "fr": "Jour 2 - chap2 Arrays, Dates, Math, Functions",
      "en": "Day 2 - chap2 Arrays, Dates, Math, Functions"
    },
    "sub": {
      "fr": "Tableaux, DateTime, fonctions mathematiques, define - CNAM chap2",
      "en": "Arrays, DateTime, math functions, define - CNAM chap2"
    },
    "tags": [
      "chap2",
      "functions",
      "arrays",
      "datetime",
      "math",
      "define"
    ],
    "why": {
      "fr": "Garanti 3-4 points : Exercice 2 recurrent depuis 2023. Maitrise les 5 patterns chap2 : arrays, DateTime, math, fonctions typees, define.",
      "en": "Guaranteed 3-4 points: recurring Exercise 2 since 2023. Master the 5 chap2 patterns: arrays, DateTime, math, typed functions, define."
    },
    "exercises": [
      {
        "num": 1,
        "title": "square",
        "diff": "easy"
      },
      {
        "num": 2,
        "title": "isEven",
        "diff": "easy"
      },
      {
        "num": 3,
        "title": "foreach fruits",
        "diff": "easy"
      },
      {
        "num": 4,
        "title": "count_words",
        "diff": "easy"
      },
      {
        "num": 5,
        "title": "capitalize",
        "diff": "easy"
      },
      {
        "num": 6,
        "title": "sum_array",
        "diff": "medium"
      },
      {
        "num": 7,
        "title": "average",
        "diff": "medium"
      },
      {
        "num": 8,
        "title": "contains_admin",
        "diff": "medium"
      },
      {
        "num": 9,
        "title": "format_amount",
        "diff": "medium"
      },
      {
        "num": 10,
        "title": "init_capitals",
        "diff": "medium"
      },
      {
        "num": 11,
        "title": "array_combine notes",
        "diff": "hard"
      },
      {
        "num": 12,
        "title": "checkSize",
        "diff": "hard"
      },
      {
        "num": 13,
        "title": "addDays",
        "diff": "hard"
      },
      {
        "num": 14,
        "title": "formatCurrency",
        "diff": "hard"
      },
      {
        "num": 15,
        "title": "checkDir",
        "diff": "hard"
      },
      {
        "num": 16,
        "title": "calculateAge",
        "diff": "extreme"
      },
      {
        "num": 17,
        "title": "isDateWithinRange",
        "diff": "extreme"
      },
      {
        "num": 18,
        "title": "surface_cercle (math chap2)",
        "diff": "extreme"
      },
      {
        "num": 19,
        "title": "define + config (chap2)",
        "diff": "extreme"
      },
      {
        "num": 20,
        "title": "stats_notes (integration chap2)",
        "diff": "extreme"
      }
    ],
    "problemes": [
      {
        "num": 101,
        "title": "Problème 05",
        "diff": "extreme"
      },
      {
        "num": 102,
        "title": "Problème 06",
        "diff": "extreme"
      },
      {
        "num": 103,
        "title": "EXAM 2023-2024 Session 1 — Ex.3 Fonctions Diverses (4 pts)",
        "diff": "extreme"
      },
      {
        "num": 104,
        "title": "EXAM 2023-2024 Session 2 — Ex.2 Fonctions Diverses (3 pts)",
        "diff": "extreme"
      }
    ]
  },
  {
    "id": "day-3",
    "code": "J3",
    "title": {
      "fr": "Jour 3 - chap3+chap4 Regex, Forms, Validation",
      "en": "Day 3 - chap3+chap4 Regex, Forms, Validation"
    },
    "sub": {
      "fr": "Regex (chap3) + Forms / filter_var / htmlspecialchars / file I/O / mkdir (chap4)",
      "en": "Regex (chap3) + Forms / filter_var / htmlspecialchars / file I/O / mkdir (chap4)"
    },
    "tags": [
      "chap3",
      "chap4",
      "regex",
      "forms",
      "POST",
      "filter_var",
      "file",
      "mkdir"
    ],
    "why": {
      "fr": "CNAM chap3+chap4 = Exercice 3 de TOUS les examens depuis 2022. Le boilerplate (valider POST + sanitize + redirect) est identique chaque annee. A memoriser ce soir.",
      "en": "CNAM chap3+chap4 = Exercise 3 of EVERY exam since 2022. The validate-POST + sanitize + redirect boilerplate is identical every year. Memorise it tonight."
    },
    "exercises": [
      {
        "num": 1,
        "title": "POST name",
        "diff": "easy"
      },
      {
        "num": 2,
        "title": "GET lang",
        "diff": "easy"
      },
      {
        "num": 3,
        "title": "isset / empty",
        "diff": "easy"
      },
      {
        "num": 4,
        "title": "Sanitize",
        "diff": "easy"
      },
      {
        "num": 5,
        "title": "Filter email",
        "diff": "easy"
      },
      {
        "num": 6,
        "title": "3 champs requis",
        "diff": "medium"
      },
      {
        "num": 7,
        "title": "GET int positif",
        "diff": "medium"
      },
      {
        "num": 8,
        "title": "Redirection",
        "diff": "medium"
      },
      {
        "num": 9,
        "title": "Radio genre",
        "diff": "medium"
      },
      {
        "num": 10,
        "title": "Select role",
        "diff": "medium"
      },
      {
        "num": 11,
        "title": "Formulaire contact",
        "diff": "hard"
      },
      {
        "num": 12,
        "title": "Reset mot de passe",
        "diff": "hard"
      },
      {
        "num": 13,
        "title": "Confirmer mot de passe",
        "diff": "hard"
      },
      {
        "num": 14,
        "title": "Checkbox multiples",
        "diff": "hard"
      },
      {
        "num": 15,
        "title": "Normaliser telephone",
        "diff": "hard"
      },
      {
        "num": 16,
        "title": "Signup NFA042 (3 champs)",
        "diff": "extreme"
      },
      {
        "num": 17,
        "title": "Login validation",
        "diff": "extreme"
      },
      {
        "num": 18,
        "title": "GET / POST / 404",
        "diff": "extreme"
      },
      {
        "num": 19,
        "title": "validate_required",
        "diff": "extreme"
      },
      {
        "num": 20,
        "title": "Signup complet",
        "diff": "extreme"
      }
    ],
    "problemes": [
      {
        "num": 101,
        "title": "Problème 08 — Regular Expression",
        "diff": "extreme"
      },
      {
        "num": 102,
        "title": "Problème 09 — Form Submission",
        "diff": "extreme"
      },
      {
        "num": 103,
        "title": "EXAM 2023-2024 Session 1 — Ex.4 Contactez-Nous (3 pts)",
        "diff": "extreme"
      }
    ]
  },
  {
    "id": "day-4",
    "code": "J4",
    "title": {
      "fr": "Jour 4 - chap5 MySQL + PDO + CRUD",
      "en": "Day 4 - chap5 MySQL + PDO + CRUD"
    },
    "sub": {
      "fr": "CNAM chap5 - l'exercice le plus lourd : 5-9 points chaque annee",
      "en": "CNAM chap5 - the heaviest exercise: 5-9 points every year"
    },
    "tags": [
      "chap5",
      "mysql",
      "PDO",
      "mysqli",
      "prepared",
      "CRUD"
    ],
    "why": {
      "fr": "CNAM chap5 (PDO.docx, sqli.docx) = exercice 5 de TOUS les examens. Maitrise les prepared statements et tu gagnes 5-9 pts garantis. <strong>Jour le plus critique de la semaine.</strong>",
      "en": "CNAM chap5 (PDO.docx, sqli.docx) = exercise 5 of EVERY exam. Master prepared statements and you bank 5-9 guaranteed points. <strong>Most critical day of the week.</strong>"
    },
    "exercises": [
      {
        "num": 1,
        "title": "mysqli connect",
        "diff": "easy"
      },
      {
        "num": 2,
        "title": "PDO connect",
        "diff": "easy"
      },
      {
        "num": 3,
        "title": "SELECT COUNT",
        "diff": "easy"
      },
      {
        "num": 4,
        "title": "INSERT prepare (mysqli)",
        "diff": "easy"
      },
      {
        "num": 5,
        "title": "SELECT all PDO",
        "diff": "easy"
      },
      {
        "num": 6,
        "title": "getUserByEmail",
        "diff": "medium"
      },
      {
        "num": 7,
        "title": "createUser",
        "diff": "medium"
      },
      {
        "num": 8,
        "title": "updateUserRole",
        "diff": "medium"
      },
      {
        "num": 9,
        "title": "Liste utilisateurs HTML",
        "diff": "medium"
      },
      {
        "num": 10,
        "title": "Recherche LIKE",
        "diff": "medium"
      },
      {
        "num": 11,
        "title": "campaign_list",
        "diff": "hard"
      },
      {
        "num": 12,
        "title": "campaign_create",
        "diff": "hard"
      },
      {
        "num": 13,
        "title": "campaign_edit",
        "diff": "hard"
      },
      {
        "num": 14,
        "title": "campaign_delete",
        "diff": "hard"
      },
      {
        "num": 15,
        "title": "INNER JOIN",
        "diff": "hard"
      },
      {
        "num": 16,
        "title": "INSERT matiere (exam)",
        "diff": "extreme"
      },
      {
        "num": 17,
        "title": "modifier_matiere",
        "diff": "extreme"
      },
      {
        "num": 18,
        "title": "Login PDO (Final 2025)",
        "diff": "extreme"
      },
      {
        "num": 19,
        "title": "JOIN a 3 tables",
        "diff": "extreme"
      },
      {
        "num": 20,
        "title": "CRUD avec role org",
        "diff": "extreme"
      }
    ],
    "problemes": [
      {
        "num": 101,
        "title": "Problème 11 — Gestion des Étudiants",
        "diff": "extreme"
      },
      {
        "num": 102,
        "title": "Problème 12 — Gestion des Étudiants",
        "diff": "extreme"
      },
      {
        "num": 103,
        "title": "EXAM 2023-2024 Session 2 — Ex.4 Matière Cnam (9 pts)",
        "diff": "extreme"
      }
    ]
  },
  {
    "id": "day-5",
    "code": "J5",
    "title": {
      "fr": "Jour 5 - chap7 Sessions, Cookies, Auth",
      "en": "Day 5 - chap7 Sessions, Cookies, Auth"
    },
    "sub": {
      "fr": "CNAM chap7 - session_start, $_SESSION, password_hash, login flow",
      "en": "CNAM chap7 - session_start, $_SESSION, password_hash, login flow"
    },
    "tags": [
      "chap7",
      "session",
      "cookie",
      "auth",
      "password_hash",
      "login"
    ],
    "why": {
      "fr": "CNAM chap7 (Les sessions.docx, header.docx, La fonction setcookie.docx, TD 12.docx) = Final 2025 Q1 (login complet avec password_verify + sessions + PDO). Le pattern est identique chaque annee.",
      "en": "CNAM chap7 (sessions, header, setcookie, TD12) = 2025 Q1 final (full login with password_verify + sessions + PDO). Identical pattern every year."
    },
    "exercises": [
      {
        "num": 1,
        "title": "Session counter",
        "diff": "easy"
      },
      {
        "num": 2,
        "title": "Cookie theme",
        "diff": "easy"
      },
      {
        "num": 3,
        "title": "Hash mot de passe",
        "diff": "easy"
      },
      {
        "num": 4,
        "title": "Verify password",
        "diff": "easy"
      },
      {
        "num": 5,
        "title": "Logout",
        "diff": "easy"
      },
      {
        "num": 6,
        "title": "Auth guard",
        "diff": "medium"
      },
      {
        "num": 7,
        "title": "Flash message",
        "diff": "medium"
      },
      {
        "num": 8,
        "title": "Login hardcoded",
        "diff": "medium"
      },
      {
        "num": 9,
        "title": "Header dynamique",
        "diff": "medium"
      },
      {
        "num": 10,
        "title": "Admin only",
        "diff": "medium"
      },
      {
        "num": 11,
        "title": "Remember me",
        "diff": "hard"
      },
      {
        "num": 12,
        "title": "Rate limiter",
        "diff": "hard"
      },
      {
        "num": 13,
        "title": "Wizard multi-etapes",
        "diff": "hard"
      },
      {
        "num": 14,
        "title": "Redirect par role",
        "diff": "hard"
      },
      {
        "num": 15,
        "title": "CSRF token",
        "diff": "hard"
      },
      {
        "num": 16,
        "title": "Login PDO (Final 2025)",
        "diff": "extreme"
      },
      {
        "num": 17,
        "title": "Reset password DB",
        "diff": "extreme"
      },
      {
        "num": 18,
        "title": "Login CNAM + role",
        "diff": "extreme"
      },
      {
        "num": 19,
        "title": "Changer mot de passe",
        "diff": "extreme"
      },
      {
        "num": 20,
        "title": "auth_check.php",
        "diff": "extreme"
      }
    ],
    "problemes": [
      {
        "num": 101,
        "title": "Problème 13 — Login / Logout",
        "diff": "extreme"
      },
      {
        "num": 102,
        "title": "Problème 14 — Login / Logout",
        "diff": "extreme"
      },
      {
        "num": 103,
        "title": "EXAM 2023-2024 Session 2 — Ex.3 Réinitialisation du mot de passe (6 pts)",
        "diff": "extreme"
      }
    ]
  },
  {
    "id": "day-6",
    "code": "J6",
    "title": {
      "fr": "Jour 6 - chap4 avance : Upload + CSV / JSON",
      "en": "Day 6 - chap4 advanced: Upload + CSV / JSON"
    },
    "sub": {
      "fr": "Final 2025 Q3 (upload + mkdir) + Q4 (export CSV). Present dans 4/5 examens (3-8 points)",
      "en": "Final 2025 Q3 (upload + mkdir) + Q4 (CSV export). Present in 4/5 past exams (3-8 points)"
    },
    "tags": [
      "chap4",
      "upload",
      "CSV",
      "JSON",
      "files",
      "mkdir",
      "move_uploaded_file",
      "Final2025"
    ],
    "why": {
      "fr": "Q3-Q4 du Final 2025. L'upload trompe beaucoup d'etudiants a cause de mkdir recursif et move_uploaded_file. Le boilerplate est court — a memoriser.",
      "en": "Q3-Q4 of Final 2025. Upload trips up many students because of recursive mkdir and move_uploaded_file. The boilerplate is short — memorise it."
    },
    "exercises": [
      {
        "num": 1,
        "title": "Formulaire upload",
        "diff": "easy"
      },
      {
        "num": 2,
        "title": "Taille en KB",
        "diff": "easy"
      },
      {
        "num": 3,
        "title": "Extension lowercase",
        "diff": "easy"
      },
      {
        "num": 4,
        "title": "Verifier PDF",
        "diff": "easy"
      },
      {
        "num": 5,
        "title": "mkdir recursif",
        "diff": "easy"
      },
      {
        "num": 6,
        "title": "Validation PDF <=1Mo",
        "diff": "medium"
      },
      {
        "num": 7,
        "title": "uniqid rename",
        "diff": "medium"
      },
      {
        "num": 8,
        "title": "Dossier date Y/m/d",
        "diff": "medium"
      },
      {
        "num": 9,
        "title": "CSV vers tableau HTML",
        "diff": "medium"
      },
      {
        "num": 10,
        "title": "CSV append",
        "diff": "medium"
      },
      {
        "num": 11,
        "title": "Upload image PNG/JPG",
        "diff": "hard"
      },
      {
        "num": 12,
        "title": "Tail log (10 dernieres)",
        "diff": "hard"
      },
      {
        "num": 13,
        "title": "Form vers JSON",
        "diff": "hard"
      },
      {
        "num": 14,
        "title": "Upload multiple",
        "diff": "hard"
      },
      {
        "num": 15,
        "title": "safe_save() reutilisable",
        "diff": "hard"
      },
      {
        "num": 16,
        "title": "Upload 2022-23 (exam)",
        "diff": "extreme"
      },
      {
        "num": 17,
        "title": "Carriere 2023-24",
        "diff": "extreme"
      },
      {
        "num": 18,
        "title": "jobPosting (Final 2025)",
        "diff": "extreme"
      },
      {
        "num": 19,
        "title": "CSV employes",
        "diff": "extreme"
      },
      {
        "num": 20,
        "title": "Images de campagne (multi-upload)",
        "diff": "extreme"
      }
    ],
    "problemes": [
      {
        "num": 101,
        "title": "Problème 07",
        "diff": "extreme"
      },
      {
        "num": 102,
        "title": "Problème 10 — File Upload",
        "diff": "extreme"
      },
      {
        "num": 103,
        "title": "Problème 15 — Upload de fichier CSV et insertion de",
        "diff": "extreme"
      },
      {
        "num": 104,
        "title": "EXAM 2023-2024 Session 1 — Ex.5 Carrière (8 pts)",
        "diff": "extreme"
      }
    ]
  },
  {
    "id": "day-7",
    "code": "J7",
    "title": {
      "fr": "Jour 7 - chap8 OOP + Mock Exam Final 2025",
      "en": "Day 7 - chap8 OOP + Mock Exam Final 2025"
    },
    "sub": {
      "fr": "CNAM chap8 (POO) + dry-run examen 120 min calibre sur Final 2025",
      "en": "CNAM chap8 (OOP) + 120-min exam dry-run calibrated on Final 2025"
    },
    "tags": [
      "chap8",
      "OOP",
      "classes",
      "inheritance",
      "mock-exam",
      "Final2025"
    ],
    "why": {
      "fr": "CNAM chap8 (POO) apparait dans 2/5 examens (3 pts a chaque fois). Pattern identique : 1 classe, props privees, constructor, 1 methode, instance, appel. Puis le Mock final couvre Q1-Q4 du Final 2025.",
      "en": "CNAM chap8 (OOP) shows up in 2/5 exams (3 pts each time). Identical pattern: 1 class, private props, constructor, 1 method, instance, call. Then the Mock covers Q1-Q4 of Final 2025."
    },
    "exercises": [
      {
        "num": 1,
        "title": "Hello class",
        "diff": "easy"
      },
      {
        "num": 2,
        "title": "Point (x, y)",
        "diff": "easy"
      },
      {
        "num": 3,
        "title": "Counter prive",
        "diff": "easy"
      },
      {
        "num": 4,
        "title": "Rectangle",
        "diff": "easy"
      },
      {
        "num": 5,
        "title": "__toString",
        "diff": "easy"
      },
      {
        "num": 6,
        "title": "Produit (exam type)",
        "diff": "medium"
      },
      {
        "num": 7,
        "title": "BankAccount",
        "diff": "medium"
      },
      {
        "num": 8,
        "title": "MathHelper::factorial",
        "diff": "medium"
      },
      {
        "num": 9,
        "title": "Panier (Cart)",
        "diff": "medium"
      },
      {
        "num": 10,
        "title": "Date wrapper",
        "diff": "medium"
      },
      {
        "num": 11,
        "title": "Validator chainable",
        "diff": "hard"
      },
      {
        "num": 12,
        "title": "User from array",
        "diff": "hard"
      },
      {
        "num": 13,
        "title": "Heritage Person",
        "diff": "hard"
      },
      {
        "num": 14,
        "title": "Campaign::find",
        "diff": "hard"
      },
      {
        "num": 15,
        "title": "Donation + SUM",
        "diff": "hard"
      },
      {
        "num": 16,
        "title": "User complet (Sawa)",
        "diff": "extreme"
      },
      {
        "num": 17,
        "title": "Campaign complet",
        "diff": "extreme"
      },
      {
        "num": 18,
        "title": "FormRequest",
        "diff": "extreme"
      },
      {
        "num": 19,
        "title": "Repository interface",
        "diff": "extreme"
      },
      {
        "num": 20,
        "title": "Strategie — 120 min",
        "diff": "extreme"
      }
    ],
    "problemes": [
      {
        "num": 101,
        "title": "🏁 MOCK 1 — Final 2025 Q1 : checkLogin.php (4 pts)",
        "diff": "extreme"
      },
      {
        "num": 102,
        "title": "🏁 MOCK 2 — Final 2025 Q2 : checkDir + isDateWithinRange (2 pts)",
        "diff": "extreme"
      },
      {
        "num": 103,
        "title": "🏁 MOCK 3 — Final 2025 Q3 : jobPosting.php (8 pts)",
        "diff": "extreme"
      },
      {
        "num": 104,
        "title": "🏁 MOCK 4 — Final 2025 Q4 : CSV addEmployee + displayEmployees (4 pts)",
        "diff": "extreme"
      },
      {
        "num": 105,
        "title": "🏁 MOCK 5 — QCM rapide (2 pts)",
        "diff": "extreme"
      },
      {
        "num": 106,
        "title": "Problème 16 — Classe Livre",
        "diff": "extreme"
      },
      {
        "num": 107,
        "title": "EXAM 2023-2024 Session 1 — Ex.2 Classe Produit (3 pts)",
        "diff": "extreme"
      }
    ]
  }
];
const W3SCHOOL = [
  {
    "id": "w3-intro",
    "code": "B1",
    "title": {
      "fr": "PHP Intro",
      "en": "PHP Intro"
    },
    "sub": {
      "fr": "Qu'est-ce que PHP, ce qu'il peut faire, premier script",
      "en": "What PHP is, what it can do, first script"
    },
    "tags": [
      "intro",
      "basics"
    ],
    "level": "basic",
    "exercises": [],
    "problemes": []
  },
  {
    "id": "w3-syntax",
    "code": "B2",
    "title": {
      "fr": "PHP Syntax",
      "en": "PHP Syntax"
    },
    "sub": {
      "fr": "Balises, instructions, commentaires, casse",
      "en": "Tags, statements, comments, case sensitivity"
    },
    "tags": [
      "syntax",
      "basics"
    ],
    "level": "basic",
    "exercises": [],
    "problemes": []
  },
  {
    "id": "w3-variables",
    "code": "B3",
    "title": {
      "fr": "PHP Variables",
      "en": "PHP Variables"
    },
    "sub": {
      "fr": "Declaration, regles de nommage, scope",
      "en": "Declaration, naming rules, scope"
    },
    "tags": [
      "variables",
      "basics"
    ],
    "level": "basic",
    "exercises": [],
    "problemes": []
  },
  {
    "id": "w3-echo",
    "code": "B4",
    "title": {
      "fr": "PHP Echo / Print",
      "en": "PHP Echo / Print"
    },
    "sub": {
      "fr": "echo vs print, short tag, printf",
      "en": "echo vs print, short tag, printf"
    },
    "tags": [
      "echo",
      "output",
      "basics"
    ],
    "level": "basic",
    "exercises": [],
    "problemes": []
  },
  {
    "id": "w3-types",
    "code": "B5",
    "title": {
      "fr": "PHP Data Types",
      "en": "PHP Data Types"
    },
    "sub": {
      "fr": "8 types : scalaires + composes + speciaux",
      "en": "8 types: scalar + compound + special"
    },
    "tags": [
      "types",
      "basics"
    ],
    "level": "basic",
    "exercises": [],
    "problemes": []
  },
  {
    "id": "w3-strings",
    "code": "B6",
    "title": {
      "fr": "PHP Strings",
      "en": "PHP Strings"
    },
    "sub": {
      "fr": "strlen, str_replace, strpos, ucfirst, number_format",
      "en": "strlen, str_replace, strpos, ucfirst, number_format"
    },
    "tags": [
      "strings",
      "basics"
    ],
    "level": "basic",
    "exercises": [],
    "problemes": []
  },
  {
    "id": "w3-numbers",
    "code": "B7",
    "title": {
      "fr": "PHP Numbers & Math",
      "en": "PHP Numbers & Math"
    },
    "sub": {
      "fr": "int, float, abs, round, sqrt, rand, IEEE 754",
      "en": "int, float, abs, round, sqrt, rand, IEEE 754"
    },
    "tags": [
      "numbers",
      "math",
      "basics"
    ],
    "level": "basic",
    "exercises": [],
    "problemes": []
  },
  {
    "id": "w3-constants",
    "code": "B8",
    "title": {
      "fr": "PHP Constants",
      "en": "PHP Constants"
    },
    "sub": {
      "fr": "define(), const, constantes magiques",
      "en": "define(), const, magic constants"
    },
    "tags": [
      "constants",
      "basics"
    ],
    "level": "basic",
    "exercises": [],
    "problemes": []
  },
  {
    "id": "w3-operators",
    "code": "B9",
    "title": {
      "fr": "PHP Operators",
      "en": "PHP Operators"
    },
    "sub": {
      "fr": "Arithmetique, comparaison, logique, ternaire, ??",
      "en": "Arithmetic, comparison, logical, ternary, ??"
    },
    "tags": [
      "operators",
      "basics"
    ],
    "level": "basic",
    "exercises": [],
    "problemes": []
  },
  {
    "id": "w3-if",
    "code": "B10",
    "title": {
      "fr": "PHP If / Else / Switch",
      "en": "PHP If / Else / Switch"
    },
    "sub": {
      "fr": "Branchements, syntaxe alternative, match (PHP 8)",
      "en": "Branches, alternative syntax, match (PHP 8)"
    },
    "tags": [
      "control-flow",
      "basics"
    ],
    "level": "basic",
    "exercises": [],
    "problemes": []
  },
  {
    "id": "w3-loops",
    "code": "B11",
    "title": {
      "fr": "PHP Loops",
      "en": "PHP Loops"
    },
    "sub": {
      "fr": "while, do-while, for, foreach, break, continue",
      "en": "while, do-while, for, foreach, break, continue"
    },
    "tags": [
      "loops",
      "basics"
    ],
    "level": "basic",
    "exercises": [],
    "problemes": []
  },
  {
    "id": "w3-functions-basic",
    "code": "B12",
    "title": {
      "fr": "PHP Functions",
      "en": "PHP Functions"
    },
    "sub": {
      "fr": "Declaration, parametres, return, type hints",
      "en": "Declaration, parameters, return, type hints"
    },
    "tags": [
      "functions",
      "basics"
    ],
    "level": "basic",
    "exercises": [],
    "problemes": []
  },
  {
    "id": "w3-arrays-basic",
    "code": "B13",
    "title": {
      "fr": "PHP Arrays",
      "en": "PHP Arrays"
    },
    "sub": {
      "fr": "Indexes, associatifs, multidimensionnels",
      "en": "Indexed, associative, multidimensional"
    },
    "tags": [
      "arrays",
      "basics"
    ],
    "level": "basic",
    "exercises": [],
    "problemes": []
  },
  {
    "id": "w3-superglobals",
    "code": "B14",
    "title": {
      "fr": "PHP Superglobals",
      "en": "PHP Superglobals"
    },
    "sub": {
      "fr": "$_GET, $_POST, $_SERVER, $_SESSION, $_COOKIE, $_FILES",
      "en": "$_GET, $_POST, $_SERVER, $_SESSION, $_COOKIE, $_FILES"
    },
    "tags": [
      "superglobals",
      "basics"
    ],
    "level": "basic",
    "exercises": [],
    "problemes": []
  },
  {
    "id": "w3-forms",
    "code": "I1",
    "title": {
      "fr": "PHP Form Handling",
      "en": "PHP Form Handling"
    },
    "sub": {
      "fr": "POST/GET, securite, pattern PRG",
      "en": "POST/GET, security, PRG pattern"
    },
    "tags": [
      "forms",
      "POST",
      "intermediate"
    ],
    "level": "intermediate",
    "exercises": [],
    "problemes": []
  },
  {
    "id": "w3-validation",
    "code": "I2",
    "title": {
      "fr": "PHP Form Validation",
      "en": "PHP Form Validation"
    },
    "sub": {
      "fr": "filter_var, required, sanitize, repopulation",
      "en": "filter_var, required, sanitize, repopulation"
    },
    "tags": [
      "forms",
      "validation",
      "intermediate"
    ],
    "level": "intermediate",
    "exercises": [],
    "problemes": []
  },
  {
    "id": "w3-regex",
    "code": "I3",
    "title": {
      "fr": "PHP RegEx",
      "en": "PHP RegEx"
    },
    "sub": {
      "fr": "preg_match, preg_replace, patterns essentiels",
      "en": "preg_match, preg_replace, essential patterns"
    },
    "tags": [
      "regex",
      "intermediate"
    ],
    "level": "intermediate",
    "exercises": [],
    "problemes": []
  },
  {
    "id": "w3-date",
    "code": "I4",
    "title": {
      "fr": "PHP Date and Time",
      "en": "PHP Date and Time"
    },
    "sub": {
      "fr": "date(), DateTime, createFromFormat",
      "en": "date(), DateTime, createFromFormat"
    },
    "tags": [
      "date",
      "intermediate"
    ],
    "level": "intermediate",
    "exercises": [],
    "problemes": []
  },
  {
    "id": "w3-include",
    "code": "I5",
    "title": {
      "fr": "PHP Include & Require",
      "en": "PHP Include & Require"
    },
    "sub": {
      "fr": "include, require, _once, __DIR__",
      "en": "include, require, _once, __DIR__"
    },
    "tags": [
      "include",
      "intermediate"
    ],
    "level": "intermediate",
    "exercises": [],
    "problemes": []
  },
  {
    "id": "w3-file",
    "code": "I6",
    "title": {
      "fr": "PHP File Handling",
      "en": "PHP File Handling"
    },
    "sub": {
      "fr": "fopen, fread, fwrite, file_get_contents, CSV",
      "en": "fopen, fread, fwrite, file_get_contents, CSV"
    },
    "tags": [
      "files",
      "intermediate"
    ],
    "level": "intermediate",
    "exercises": [],
    "problemes": []
  },
  {
    "id": "w3-upload",
    "code": "I7",
    "title": {
      "fr": "PHP File Upload",
      "en": "PHP File Upload"
    },
    "sub": {
      "fr": "enctype, $_FILES, move_uploaded_file, validation",
      "en": "enctype, $_FILES, move_uploaded_file, validation"
    },
    "tags": [
      "upload",
      "intermediate"
    ],
    "level": "intermediate",
    "exercises": [],
    "problemes": []
  },
  {
    "id": "w3-cookies",
    "code": "I8",
    "title": {
      "fr": "PHP Cookies",
      "en": "PHP Cookies"
    },
    "sub": {
      "fr": "setcookie, $_COOKIE, expiration",
      "en": "setcookie, $_COOKIE, expiration"
    },
    "tags": [
      "cookies",
      "intermediate"
    ],
    "level": "intermediate",
    "exercises": [],
    "problemes": []
  },
  {
    "id": "w3-sessions",
    "code": "I9",
    "title": {
      "fr": "PHP Sessions",
      "en": "PHP Sessions"
    },
    "sub": {
      "fr": "session_start, $_SESSION, regenerate_id, destroy",
      "en": "session_start, $_SESSION, regenerate_id, destroy"
    },
    "tags": [
      "sessions",
      "intermediate"
    ],
    "level": "intermediate",
    "exercises": [],
    "problemes": []
  },
  {
    "id": "w3-json",
    "code": "I10",
    "title": {
      "fr": "PHP JSON",
      "en": "PHP JSON"
    },
    "sub": {
      "fr": "json_encode, json_decode, API REST",
      "en": "json_encode, json_decode, REST API"
    },
    "tags": [
      "json",
      "intermediate"
    ],
    "level": "intermediate",
    "exercises": [],
    "problemes": []
  },
  {
    "id": "w3-oop",
    "code": "A1",
    "title": {
      "fr": "PHP OOP — Intro",
      "en": "PHP OOP — Intro"
    },
    "sub": {
      "fr": "Class, object, property, method",
      "en": "Class, object, property, method"
    },
    "tags": [
      "OOP",
      "advanced"
    ],
    "level": "advanced",
    "exercises": [],
    "problemes": []
  },
  {
    "id": "w3-constructor",
    "code": "A2",
    "title": {
      "fr": "PHP Constructor / Destructor",
      "en": "PHP Constructor / Destructor"
    },
    "sub": {
      "fr": "__construct, __destruct, property promotion (PHP 8)",
      "en": "__construct, __destruct, property promotion (PHP 8)"
    },
    "tags": [
      "OOP",
      "constructor",
      "advanced"
    ],
    "level": "advanced",
    "exercises": [],
    "problemes": []
  },
  {
    "id": "w3-modifiers",
    "code": "A3",
    "title": {
      "fr": "PHP Access Modifiers",
      "en": "PHP Access Modifiers"
    },
    "sub": {
      "fr": "public, protected, private",
      "en": "public, protected, private"
    },
    "tags": [
      "OOP",
      "advanced"
    ],
    "level": "advanced",
    "exercises": [],
    "problemes": []
  },
  {
    "id": "w3-inheritance",
    "code": "A4",
    "title": {
      "fr": "PHP Inheritance",
      "en": "PHP Inheritance"
    },
    "sub": {
      "fr": "extends, parent::, override, final",
      "en": "extends, parent::, override, final"
    },
    "tags": [
      "OOP",
      "inheritance",
      "advanced"
    ],
    "level": "advanced",
    "exercises": [],
    "problemes": []
  },
  {
    "id": "w3-abstract",
    "code": "A5",
    "title": {
      "fr": "PHP Abstract Classes",
      "en": "PHP Abstract Classes"
    },
    "sub": {
      "fr": "abstract class, abstract method",
      "en": "abstract class, abstract method"
    },
    "tags": [
      "OOP",
      "abstract",
      "advanced"
    ],
    "level": "advanced",
    "exercises": [],
    "problemes": []
  },
  {
    "id": "w3-interfaces",
    "code": "A6",
    "title": {
      "fr": "PHP Interfaces",
      "en": "PHP Interfaces"
    },
    "sub": {
      "fr": "interface, implements, multi-implementation",
      "en": "interface, implements, multi-implementation"
    },
    "tags": [
      "OOP",
      "interface",
      "advanced"
    ],
    "level": "advanced",
    "exercises": [],
    "problemes": []
  },
  {
    "id": "w3-static",
    "code": "A7",
    "title": {
      "fr": "PHP Static",
      "en": "PHP Static"
    },
    "sub": {
      "fr": "static methods, static properties, self::, static::",
      "en": "static methods, static properties, self::, static::"
    },
    "tags": [
      "OOP",
      "static",
      "advanced"
    ],
    "level": "advanced",
    "exercises": [],
    "problemes": []
  },
  {
    "id": "w3-exceptions",
    "code": "A8",
    "title": {
      "fr": "PHP Exceptions",
      "en": "PHP Exceptions"
    },
    "sub": {
      "fr": "try/catch/throw/finally, hierarchie",
      "en": "try/catch/throw/finally, hierarchy"
    },
    "tags": [
      "exceptions",
      "advanced"
    ],
    "level": "advanced",
    "exercises": [],
    "problemes": []
  },
  {
    "id": "w3-mysql",
    "code": "A9",
    "title": {
      "fr": "PHP MySQL Connect",
      "en": "PHP MySQL Connect"
    },
    "sub": {
      "fr": "mysqli, PDO, prepared statements",
      "en": "mysqli, PDO, prepared statements"
    },
    "tags": [
      "mysql",
      "database",
      "advanced"
    ],
    "level": "advanced",
    "exercises": [],
    "problemes": []
  },
  {
    "id": "w3-traits",
    "code": "A10",
    "title": {
      "fr": "PHP Traits",
      "en": "PHP Traits"
    },
    "sub": {
      "fr": "Partage de code entre classes non liees",
      "en": "Code sharing across unrelated classes"
    },
    "tags": [
      "OOP",
      "traits",
      "advanced"
    ],
    "level": "advanced",
    "exercises": [],
    "problemes": []
  }
];
const ALL_LESSONS = [...DAYS, ...W3SCHOOL];
const TOTAL = ALL_LESSONS.length;
const TOTAL_EXERCISES = DAYS.reduce((s,d)=>s+(d.exercises?d.exercises.length:0)+(d.problemes?d.problemes.length:0),0);
