// One-shot: split web/js/data.js into a slim metadata file + per-lesson JSON
// details under web/data/. Re-runnable (idempotent).
//
// Slim entry shape: { id, code, level?, title, sub, why?, tags,
//                     exercises:[{num,title,diff}], problemes:[{num,title,diff}] }
// Detail JSON shape: { sections, quiz?, exercises:[full], problemes:[full] }

const fs = require("fs");
const path = require("path");
const vm = require("vm");

const root     = path.join(__dirname, "..");
const dataJs   = path.join(root, "web", "js", "data.js");
const dataDir  = path.join(root, "web", "data");
const backupJs = path.join(root, "web", "js", "data.full.js.bak");

const src = fs.readFileSync(dataJs, "utf8");

// Keep a backup once — never overwrite a pre-existing backup so we don't
// accidentally clobber the only copy of the full data after a second run.
if (!fs.existsSync(backupJs)) {
  fs.writeFileSync(backupJs, src);
  console.log("Backed up original data.js → data.full.js.bak");
}

if (!fs.existsSync(dataDir)) fs.mkdirSync(dataDir, { recursive: true });

const sandbox = {};
vm.createContext(sandbox);
vm.runInContext(src + "\nthis.__OUT = { DAYS, W3SCHOOL };", sandbox);
const { DAYS, W3SCHOOL } = sandbox.__OUT;

const exMeta = e => ({ num: e.num, title: e.title, diff: e.diff });

function slim(l) {
  const o = {
    id: l.id,
    code: l.code,
    title: l.title,
    sub: l.sub,
    tags: l.tags || [],
  };
  if (l.level)  o.level = l.level;
  if (l.why)    o.why   = l.why;
  o.exercises = (l.exercises || []).map(exMeta);
  o.problemes = (l.problemes || []).map(exMeta);
  return o;
}

function detail(l) {
  const d = {};
  if (l.sections)  d.sections  = l.sections;
  if (l.quiz)      d.quiz      = l.quiz;
  if (l.exercises) d.exercises = l.exercises;
  if (l.problemes) d.problemes = l.problemes;
  return d;
}

const slimDAYS = DAYS.map(slim);
const slimW3SCHOOL = W3SCHOOL.map(slim);

// Write per-lesson JSON details (compact: no pretty-printing → ~30% smaller)
let totalDetailBytes = 0;
for (const l of [...DAYS, ...W3SCHOOL]) {
  const json = JSON.stringify(detail(l));
  const file = path.join(dataDir, l.id + ".json");
  fs.writeFileSync(file, json);
  totalDetailBytes += json.length;
}

// Rebuild slim data.js. Pretty-print for diffability.
const out =
  "// AUTO-GENERATED by tools/split-data.js — slim metadata only.\n" +
  "// Full lesson content lives in /web/data/<id>.json and is fetched on demand.\n" +
  "const DAYS = " + JSON.stringify(slimDAYS, null, 2) + ";\n" +
  "const W3SCHOOL = " + JSON.stringify(slimW3SCHOOL, null, 2) + ";\n" +
  "const ALL_LESSONS = [...DAYS, ...W3SCHOOL];\n" +
  "const TOTAL = ALL_LESSONS.length;\n" +
  "const TOTAL_EXERCISES = DAYS.reduce((s,d)=>s+(d.exercises?d.exercises.length:0)+(d.problemes?d.problemes.length:0),0);\n";

fs.writeFileSync(dataJs, out);

const before = src.length;
const after  = out.length;
console.log("Slim data.js: " + before + " → " + after + " bytes (" +
  Math.round((1 - after / before) * 100) + "% smaller)");
console.log("Per-lesson JSON written: " + (DAYS.length + W3SCHOOL.length) +
  " files, " + totalDetailBytes + " bytes total");
